"""added constraint to author

Revision ID: 65edc1bd0fb7
Revises: d915c5715e17
Create Date: 2024-06-07 11:39:32.470689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65edc1bd0fb7'
down_revision = 'd915c5715e17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_authors_name'), ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_authors_name'), type_='unique')

    # ### end Alembic commands ###
